name: workflow-predict
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Model predict'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          # sudo -H apt update
          # sudo -H apt install python3.7 -y
          python --version
          sudo -H pip install -r requirements-prod.txt

          cd src/
          sudo -H python predict_cvae.py
          echo "TEST passed"

          echo "# Predictions distribution" > report.md
          cml-publish histogram_predictions.png --md >> report.md
          cml-send-comment report.md


